import test from 'node:test';
import assert from 'node:assert/strict';
import {ShiftGame,flowDifficulty,arrivalGap,FLOW} from '../web/src/shift-model.mjs';
import {RULES} from '../web/src/lane-model.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const fixture=(tempo=300)=>new ShiftGame({autoSpawn:false,difficultyAt:tempo});
const seeded=n=>()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/2**32);
function ideal(g){for(const c of g.cars)if(c.state==='approaching'&&c.revealed&&!c.black&&c.arrivalAt-g.time<=.32&&c.arrivalAt>g.time)g.tap(c.lane);}

test('density grows smoothly while plate reveal stays within 0..50%',()=>{let d=flowDifficulty(0);for(let t=.1;t<=300;t+=.1){const n=flowDifficulty(t);assert.ok(n.interval<=d.interval+1e-8);assert.ok(n.speed>=d.speed-1e-8);assert.ok(n.reveal>=d.reveal-1e-8&&n.reveal<=.5);assert.ok(d.interval-n.interval<.03);d=n;}near(flowDifficulty(300).interval,.4);assert.deepEqual([0,30,75,150,240].map(t=>flowDifficulty(t).maxCars),[1,2,4,6,8]);});
test('four gates have independent pulses and physical crossing awards once',()=>{const g=fixture();for(let lane=0;lane<4;lane++)assert.ok(g.spawn({lane,black:lane===3}));g.update(1.3);assert.ok(g.tap(0));assert.ok(g.tap(2));assert.equal(g.score,0);g.update(.3);assert.equal(g.score,10);assert.equal(g.lives,2);assert.equal(g.blocked,1);g.update(.3);assert.equal(g.score,10);});
test('black pass costs fifteen but no life; black blocked explodes',()=>{const g=fixture();g.spawn({lane:0,black:true});g.spawn({lane:1,black:true});g.update(1.3);g.tap(0);g.update(.3);assert.equal(g.score,-15);assert.equal(g.lives,3);assert.equal(g.penalties,1);assert.equal(g.blocked,1);});
test('shared third life stops tied fourth collision and emits one result',()=>{const g=fixture();for(let lane=0;lane<4;lane++)g.spawn({lane,black:false});g.update(1.56);assert.equal(g.lives,0);assert.equal(g.status,'finishing');assert.equal(g.tap(3),false);g.update(2);const events=g.drainEvents();assert.equal(events.filter(e=>e.type==='crash').length,3);assert.equal(events.filter(e=>e.type==='end').length,1);assert.equal(g.reason,'lives');g.update(100);assert.equal(g.drainEvents().length,0);});
test('arrival ordering applies earlier score before later fatal collision',()=>{const g=fixture();g.lives=1;g.spawn({lane:3,black:false});g.update(.1);g.spawn({lane:0,black:false});g.update(1.2);g.tap(3);g.update(.4);assert.equal(g.score,5);assert.equal(g.status,'finishing');near(g.finishedTime,1.65);});
test('same-lane queue rejects close spawns and third car; no speed catch-up',()=>{const g=fixture();g.spawn({lane:0,black:false,type:'minivan'});assert.equal(g.spawn({lane:0}),false);g.update(1.45);assert.ok(g.spawn({lane:0,black:false}));assert.equal(g.spawn({lane:0}),false);const [a,b]=g.cars;assert.ok(b.arrivalAt-a.arrivalAt>=arrivalGap(a,b.speed));assert.ok(b.speed<=a.speed);});
test('follower never overlaps a crash before its removal',()=>{const g=fixture();g.spawn({lane:0,black:false,type:'minivan'});g.update(1.45);g.spawn({lane:0,black:false,type:'truck'});while(g.time<2.52){g.update(1/120);if(g.cars.length===2){const [a,b]=g.cars;assert.ok(a.front-a.width-b.front>=FLOW.bodyGap-1e-6);}}assert.equal(g.cars.length,1);});
test('a successfully admitted long car clears before arm falls; next can be served',()=>{const g=fixture();g.spawn({lane:0,black:false,type:'minivan'});g.update(1.3);g.tap(0);g.update(.15);g.spawn({lane:0,black:false,type:'truck'});while(g.time<4){ideal(g);g.update(1/120);for(const c of g.cars)if(c.state==='passing'&&c.front-c.width-48<RULES.gateX)assert.equal(g.lanes[c.lane].gateAmount(),1);}assert.equal(g.passed,2);assert.equal(g.lives,3);});
test('one global prefix quota across lanes; first nine white and independent bodies',()=>{const g=fixture();g.random=seeded(123);let whiteBlack=0,blackWhite=0;for(let i=0;i<20000;i++){g.spawn({lane:i%4});const c=g.cars.at(-1);assert.ok(g.blackCount<=Math.floor(g.total/10));if(i<9)assert.equal(c.black,false);if(c.black&&c.color==='white')blackWhite++;if(!c.black&&c.color==='black')whiteBlack++;g.cars=[];}assert.ok(blackWhite>100);assert.ok(whiteBlack>1000);});
test('plate visibility is identical for both categories, fixed at spawn',()=>{for(const black of [true,false]){const g=fixture();g.spawn({black,lane:0});g.update(.75);assert.equal(g.cars[0].revealed,false);g.update(.05);assert.equal(g.cars[0].revealed,true);const speed=g.cars[0].speed;g.difficultyAt=0;g.update(.1);assert.equal(g.cars[0].speed,speed);assert.equal(g.cars[0].revealAt,.5);assert.equal(g.cars[0].revealed,true);}});
test('update subdivision preserves deterministic events and positions',()=>{const a=fixture(),b=fixture();for(const g of [a,b]){g.spawn({lane:0,black:false});g.spawn({lane:1,black:true});g.update(1.3);g.tap(0);}a.update(.4);for(let i=0;i<40;i++)b.update(.01);assert.equal(a.score,b.score);assert.equal(a.lives,b.lives);near(a.cars[0].front,b.cars[0].front);});
test('300 seconds terminates once; no doomed car spawns near shift end',()=>{const g=fixture();g.update(299);assert.equal(g.spawn({lane:1}),false);g.update(2);assert.equal(g.reason,'time');assert.equal(g.finishedTime,300);assert.equal(g.status,'ended');assert.equal(g.drainEvents().filter(e=>e.type==='end').length,1);const fresh=fixture();assert.equal(fresh.time,0);assert.equal(fresh.score,0);assert.equal(fresh.lives,3);assert.equal(fresh.cars.length,0);assert.ok(fresh.lanes.every(l=>l.gateAmount()===0));});
test('time-limit transition keeps already admitted cars clearing the arms',()=>{const g=fixture();g.update(298.3);g.spawn({lane:0,black:false,type:'minivan'});g.update(1.3);g.tap(0);g.update(.41);assert.equal(g.status,'finishing');const x=g.cars[0].front;g.update(.3);assert.ok(g.cars[0].front>x+200);assert.ok(g.cars[0].front-g.cars[0].width-48>RULES.gateX);});
test('invalid dt and lane, held input, repeat pulses cannot change outcomes',()=>{const g=fixture();for(const lane of [-1,4,1.2,NaN]){assert.equal(g.tap(lane),false);assert.equal(g.spawn({lane}),false);}for(const dt of [NaN,Infinity,-1,0])g.update(dt);assert.equal(g.time,0);assert.ok(g.tap(0));const until=g.lanes[0].gate.pulseUntil;g.update(.3);assert.equal(g.tap(0),false);assert.equal(g.lanes[0].gate.pulseUntil,until);assert.ok(g.tap(1));});
test('seeded full shifts obey capacity, geometry and allow perfect play',()=>{for(let seed=1;seed<=12;seed++){const g=new ShiftGame({random:seeded(seed)});let peak=0;while(g.status!=='ended'){ideal(g);g.update(1/60);peak=Math.max(peak,g.cars.length);assert.ok(g.cars.length<=flowDifficulty(g.time).maxCars);for(let lane=0;lane<4;lane++){const cars=g.cars.filter(c=>c.lane===lane);assert.ok(cars.length<=2);if(cars.length===2)assert.ok(cars[0].front-cars[0].width-cars[1].front>=FLOW.bodyGap-1e-5);}g.drainEvents();}assert.equal(g.reason,'time',`seed ${seed}`);assert.equal(g.lives,3,`seed ${seed}`);assert.equal(g.penalties,0);assert.ok(g.total>150&&peak>=6);}});
