import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'output/playwright/shift');fs.mkdirSync(out,{recursive:true});
const host=path.join(out,'host.cjs'),file=path.join(root,'web-test/index.html');
fs.writeFileSync(host,`const {app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(path.join(out,'profile'))});app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1920,height:1080,webPreferences:{contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true}});w.loadFile(${JSON.stringify(file)},{query:{test:'1'}});});app.on('window-all-closed',()=>app.quit());`);
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let app;const errors=[],report={date:new Date().toISOString(),engine:'Chromium, offscreen on current Windows PC',checks:[]};
async function check(name,fn){await fn();report.checks.push(name);console.log('PASS '+name);}
try{
 app=await electron.launch({args:[host],env,timeout:45000});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>window.__parkingShiftTest);await page.evaluate(()=>document.fonts.ready);
 const call=(method,value)=>page.evaluate(({method,value})=>window.__parkingShiftTest[method](value),{method,value});
 const state=()=>call('snapshot'),advance=dt=>call('advance',dt),reset=(o={})=>call('reset',{difficultyAt:300,...o}),spawn=o=>call('spawn',o),shot=name=>page.screenshot({path:path.join(out,name+'.png'),scale:'css'});
 const size=async(width,height)=>{await page.setViewportSize({width,height});await page.waitForFunction(([w,h])=>innerWidth===w&&innerHeight===h&&Math.abs(document.querySelector('#stage').getBoundingClientRect().height-1080*Math.min(w/1920,h/1080))<.1,[width,height]);};
 const four=async()=>{await reset();for(let lane=0;lane<4;lane++)await spawn({lane,black:false,type:['sedan','minivan','truck','crossover'][lane]});};
 const crowd=async()=>{await four();await advance(1.3);for(let lane=0;lane<4;lane++)await call('open',lane);await advance(.15);for(let lane=0;lane<4;lane++)assert.ok(await spawn({lane,black:lane===0,type:'convertible'}));await advance(.05);};

 await check('full playfield has four controls and no development panel or tempo selectors',async()=>{await size(1920,1080);if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();if(await page.locator('#tutorial-skip').isVisible())await page.locator('#tutorial-skip').click();assert.equal(await page.locator('.practice-panel,.tempo,[data-tempo]').count(),0);assert.equal(await page.locator('.gate-zone:visible').count(),4);assert.equal(await page.locator('#game-controls').isVisible(),true);assert.equal(await page.locator('#restart').isVisible(),false);assert.match(await page.locator('.key-help').innerText(),/1–4/);});
 await check('Digit1..4 and NumPad control independent gates and four simultaneous passes',async()=>{await four();await advance(1.3);await page.keyboard.press('Digit1');const s=await state();assert.ok(s.gates[0].pulseUntil>0);assert.equal(s.gates[1].pulseUntil,-Infinity);for(const key of ['Numpad2','Digit3','Numpad4'])await page.keyboard.press(key);await advance(.3);assert.equal((await state()).score,20);assert.equal((await state()).lives,3);await shot('01-four-pass');});
 await check('pointer on every lane, repeated input does not stretch any pulse',async()=>{await four();await advance(1.3);for(const lane of [0,1,2,3]){const gate=page.locator(`.gate-zone[data-lane="${lane}"]`);await gate.click();const until=(await state()).gates[lane].pulseUntil;await gate.click();assert.equal((await state()).gates[lane].pulseUntil,until);}await advance(.3);assert.equal((await state()).score,20);});
 await check('black penalty message stays above road; blocked black and driver remain lane-local',async()=>{await reset();await spawn({lane:0,black:true});await spawn({lane:1,black:true});await spawn({lane:2,black:false});await advance(1.3);await call('open',0);await advance(.3);const s=await state();assert.equal(s.score,-15);assert.equal(s.lives,2);assert.equal(s.cars[1].state,'exploded');assert.equal(s.cars[2].state,'crashed');assert.match(await page.locator('#feedback').innerText(),/Штраф 15 очков.*Столкновение/);assert.equal(await page.locator('#feedback').evaluate(e=>e.scrollWidth>e.clientWidth),false);const f=await page.locator('#feedback').boundingBox();assert.ok(f.y+f.height<=210);await shot('02-mixed-outcomes');});
 await check('all eight cars, five body types and four plates fit both target resolutions',async()=>{for(const [w,h] of [[1920,1080],[1366,768]]){await size(w,h);await crowd();assert.equal((await state()).cars.length,8);assert.equal(await page.locator('#vehicles>.car').count(),8);assert.equal(await page.locator('.plate:not(.hidden):not(.resolved)').count(),4);const geometry=await page.evaluate(()=>{const stage=document.querySelector('#stage').getBoundingClientRect(),scale=stage.width/1920;return [...document.querySelectorAll('.plate:not(.hidden):not(.resolved)')].map(p=>{const r=p.getBoundingClientRect(),g=document.querySelector(`.gate-zone[data-lane="${p.dataset.lane}"]`).getBoundingClientRect();return {lane:Number(p.dataset.lane),x:(r.x-stage.x)/scale,y:(r.y-stage.y)/scale,width:r.width/scale,height:r.height/scale,gateX:(g.x-stage.x)/scale};});});for(const p of geometry){const y=[210,400,590,780][p.lane];assert.ok(p.y>=y&&p.y+p.height<=y+190);assert.ok(p.x+p.width<=p.gateX);}await shot('03-eight-cars-'+w);await advance(.75);assert.equal(await page.locator('.plate:not(.hidden):not(.resolved)').count(),4);await shot('04-next-plates-'+w);}});
 await check('same-lane plates remain separate during continuous approach',async()=>{await size(1920,1080);await reset({difficultyAt:75});assert.ok(await spawn({lane:3,black:false,type:'sedan'}));await advance(1.94);assert.ok(await spawn({lane:3,black:false,type:'minivan'}));for(let i=0;i<46;i++){const s=await state();for(const c of s.cars)if(c.state==='approaching'&&!c.black&&c.arrivalAt-s.time<=.32)await call('open',c.lane);await advance(.04);const bounds=await page.locator('.plate:not(.hidden):not(.resolved)').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().toJSON()).sort((a,b)=>a.x-b.x));if(bounds.length===2)assert.ok(bounds[0].x+bounds[0].width+10<=bounds[1].x);}await shot('05-queue');});
 await check('third shared loss produces one result; restart empties all four lanes and gates',async()=>{await four();await advance(2.5);assert.equal((await state()).mode,'result');assert.equal((await state()).lives,0);await shot('06-result');if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();const s=await state();assert.equal(s.time,0);assert.equal(s.score,0);assert.equal(s.lives,3);assert.equal(s.cars.length,0);assert.ok(s.gates.every(g=>g.amount===0));assert.equal(await page.locator('#vehicles>.car,.plate').count(),0);assert.equal(await page.locator('#effects').innerHTML(),'');});
 await check('pause freezes every car and gate; hidden page pauses; restart is available inside pause',async()=>{await crowd();await page.locator('#pause').click();const before=await state();await advance(10);assert.deepEqual((await state()).cars,before.cars);assert.deepEqual((await state()).gates,before.gates);if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;});assert.equal((await state()).mode,'paused');assert.equal(await page.locator('#restart').isVisible(),true);await page.locator('#restart').click();assert.equal((await state()).cars.length,0);});
 await check('real renderer runs the complete 300-second shift without stale cars or errors',async()=>{if(await page.locator('#sound').getAttribute('aria-pressed')==='true')await page.locator('#sound').click();await reset({difficultyAt:null,autoSpawn:true});const result=await page.evaluate(()=>{const h=window.__parkingShiftTest,durations=[];let peak=0;for(let tick=0;tick<9100;tick++){const s=h.snapshot();if(s.status==='ended')break;for(const c of s.cars)if(c.state==='approaching'&&c.revealed&&!c.black&&c.arrivalAt-s.time<=.32)h.open(c.lane);const start=performance.now();h.advance(1/30);durations.push(performance.now()-start);peak=Math.max(peak,h.snapshot().cars.length);}durations.sort((a,b)=>a-b);return {state:h.snapshot(),peak,steps:durations.length,renderStepP95:durations[Math.floor(durations.length*.95)],maxStep:durations.at(-1)};});assert.equal(result.state.reason,'time');assert.equal(result.state.lives,3);assert.equal(result.state.mode,'result');assert.ok(result.peak>=6);assert.ok(result.state.score>1000);report.acceleratedRenderer={steps:result.steps,peak:result.peak,stepP95ms:result.renderStepP95,maxStepMs:result.maxStep,score:result.state.score};await shot('07-five-minute-result');});
 await check('six-second real-time final-flow sample records rendering performance',async()=>{await reset({difficultyAt:300,autoSpawn:true});await call('realtime');report.realTimeSample=await page.evaluate(()=>new Promise(resolve=>{const h=window.__parkingShiftTest,begin=performance.now(),intervals=[];let last=begin,peak=0;function sample(now){intervals.push(now-last);last=now;const s=h.snapshot();peak=Math.max(peak,s.cars.length);for(const c of s.cars)if(c.state==='approaching'&&c.revealed&&!c.black&&c.arrivalAt-s.time<=.32)h.open(c.lane);if(now-begin>=6000){intervals.sort((a,b)=>a-b);resolve({elapsedMs:now-begin,frames:intervals.length,meanFps:1000*intervals.length/(now-begin),p95FrameMs:intervals[Math.floor(intervals.length*.95)],peak,gameTime:h.snapshot().time});}else requestAnimationFrame(sample);}requestAnimationFrame(sample);}));assert.ok(report.realTimeSample.gameTime>4);assert.ok(report.realTimeSample.peak>=4);});
 await check('training remains separate and skip returns to four clean lanes',async()=>{await page.evaluate(()=>window.__parkingTutorialTest.start());assert.equal(await page.locator('#game-controls').isVisible(),false);await page.locator('#tutorial-skip').click();assert.equal(await page.locator('.gate-zone:visible').count(),4);assert.equal((await state()).cars.length,0);assert.equal((await state()).lives,3);});
 await check('font, no external assets, no runtime exceptions',async()=>{assert.equal(await page.evaluate(()=>document.fonts.check('40px Pixel')),true);assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>/^https?:/.test(r.name)).map(r=>r.name)),[]);});
 report.status='PASS';
}catch(error){report.status='FAIL';report.error=error.stack;console.error(error);process.exitCode=1;}
finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));if(app)await app.close();}
