import test from 'node:test';
import assert from 'node:assert/strict';
import {Tutorial} from '../web/src/tutorial.mjs';

function first(t){t.next();t.update(5);assert.equal(t.phase,'tap');t.tap(1);t.update(4);assert.equal(t.phase,'success');}
function second(t){first(t);t.next();t.update(4.55);t.tap(0);t.update(3);assert.equal(t.phase,'success');}
function third(t){second(t);t.next();t.next();t.update(6);assert.equal(t.phase,'success');}

test('reading plate freezes physics, with no implied tap',()=>{const t=new Tutorial();t.update(90);assert.equal(t.time,0);assert.equal(t.view().plateLane,1);assert.equal(t.view().fingerLane,null);assert.equal(t.tap(1),false);assert.equal(t.games[1].car.revealed,true);});
test('finger waits indefinitely for the correct actual input',()=>{const t=new Tutorial();t.next();t.update(5);const time=t.time,front=t.games[1].car.front;t.update(60);assert.equal(t.time,time);assert.equal(t.games[1].car.front,front);assert.equal(t.fingerLane,1);assert.equal(t.tap(0),false);assert.equal(t.games[1].gateAmount(),0);assert.equal(t.tap(1),true);assert.equal(t.fingerLane,null);assert.match(t.view().title,/проезжает/);t.update(4);assert.equal(t.phase,'success');assert.equal(t.score,5);});
test('independent attempt uses another lane without a finger',()=>{const t=new Tutorial();first(t);t.next();assert.equal(t.games[0].car.lane,0);assert.equal(t.fingerLane,null);t.update(4.55);assert.equal(t.tap(0),true);t.update(3);assert.equal(t.phase,'success');assert.equal(t.score,5);});
test('missed white car is safe and retry adds timing assistance',()=>{const t=new Tutorial();first(t);t.next();t.update(6);assert.equal(t.phase,'retry');assert.equal(t.games[0].lives,3);assert.equal(t.games[0].status,'running');t.next();t.update(6);assert.equal(t.phase,'tap');assert.equal(t.fingerLane,0);t.tap(0);t.update(4);assert.equal(t.phase,'success');});
test('black instruction freezes only until acknowledgement, then no input wins',()=>{const t=new Tutorial();second(t);t.next();const time=t.time;t.update(20);assert.equal(t.time,time);assert.equal(t.view().plateLane,2);assert.equal(t.fingerLane,null);t.next();t.update(6);assert.equal(t.phase,'success');assert.equal(t.score,0);assert.equal(t.games[2].lives,3);assert.ok(t.drainEvents().some(e=>e.type==='explode'));});
test('opening for black car yields safe retry, never an open-gate finger',()=>{const t=new Tutorial();second(t);t.next();t.next();t.update(4.55);t.tap(2);t.update(2);assert.equal(t.phase,'retry');assert.equal(t.games[2].lives,3);assert.equal(t.games[2].score,0);t.next();assert.equal(t.phase,'black_read');t.next();t.update(6);assert.equal(t.phase,'success');assert.equal(t.fingerLane,null);});
test('two independent cars arrive 1.25 seconds apart and complete the course',()=>{const t=new Tutorial();third(t);t.next();assert.equal(t.games.filter(g=>g.car).length,1);t.update(1.25);assert.equal(t.games.filter(g=>g.car).length,2);t.update(3.3);t.tap(0);t.update(1.25);t.tap(1);t.update(4);assert.equal(t.phase,'complete');assert.equal(t.score,10);assert.equal(t.next(),'complete');});
test('failed pair retries with each gate highlighted in sequence',()=>{const t=new Tutorial();third(t);t.next();t.update(7);assert.equal(t.phase,'retry');t.next();t.update(7);assert.equal(t.fingerLane,0);t.tap(0);t.update(7);assert.equal(t.fingerLane,1);t.tap(1);t.update(4);assert.equal(t.phase,'complete');assert.deepEqual(t.games.map(g=>g.lives),[3,3,3,3]);});
test('large and small updates reach the same guide boundary',()=>{const a=new Tutorial(),b=new Tutorial();a.next();b.next();a.update(5);for(let i=0;i<600;i++)b.update(1/120);assert.equal(a.phase,b.phase);assert.ok(Math.abs(a.time-b.time)<1e-8);assert.equal(a.games[1].car.front,b.games[1].car.front);});
test('invalid elapsed times and inactive controls do not change state',()=>{const t=new Tutorial();for(const dt of [NaN,Infinity,-1,0])t.update(dt);assert.equal(t.time,0);for(const lane of [-1,0,1,2,3,4])assert.equal(t.tap(lane),false);t.next();assert.equal(t.next(),false);assert.equal(t.tap(1),false);});
