import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'output/playwright/tutorial');fs.mkdirSync(out,{recursive:true});
const host=path.join(out,'host.cjs'),file=path.join(root,'web-test/index.html');
fs.writeFileSync(host,`const {app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(path.join(out,'profile'))});app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1920,height:1080,webPreferences:{contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true}});w.loadFile(${JSON.stringify(file)},{query:{test:'1'}});});app.on('window-all-closed',()=>app.quit());`);
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let app;const errors=[],report={date:new Date().toISOString(),engine:'Chromium, local web bundle',checks:[]};
async function check(name,fn){await fn();report.checks.push(name);console.log('PASS '+name);}
try{
 app=await electron.launch({args:[host],env,timeout:45000});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>window.__parkingTutorialTest);await page.evaluate(()=>document.fonts.ready);await page.setViewportSize({width:1920,height:1080});
 const hook=(method,value)=>page.evaluate(({method,value})=>window.__parkingTutorialTest[method](value),{method,value});
 const state=()=>hook('snapshot'),advance=dt=>hook('advance',dt),next=()=>page.locator('#tutorial-next').click(),shot=name=>page.screenshot({path:path.join(out,name+'.png'),scale:'css'});
 const first=async()=>{await hook('start');await next();await advance(5);await page.keyboard.press('Digit2');await advance(4);await next();};
 const black=async()=>{await first();await advance(4.55);await page.keyboard.press('Digit1');await advance(3);await next();};
 const pair=async()=>{await black();await next();await advance(6);await next();};
 function clean(s){assert.equal(s.mode,'playing');assert.equal(s.tutorial,null);assert.deepEqual(s.game,{time:0,score:0,lives:3,total:0});}

 await check('first start teaches; plate belongs to one car, clock is frozen',async()=>{await hook('clearSeen');assert.match(await page.locator('#entry-hint').innerText(),/обучения/);if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();assert.equal((await state()).mode,'tutorial');await hook('start');await advance(30);assert.equal((await state()).tutorial.time,0);assert.equal(await page.locator('#time').innerText(),'УЧЁБА');assert.equal(await page.locator('.plate.tutorial-focus').count(),1);assert.equal(await page.locator('#tutorial-finger').isVisible(),false);await shot('01-read-plate');});
 await check('animated finger freezes car until actual correct pointer input',async()=>{await next();await advance(5);const s=await state();assert.equal(s.tutorial.phase,'tap');assert.equal(await page.locator('#tutorial-finger').isVisible(),true);assert.equal(await page.locator('#tutorial-finger').evaluate(e=>getComputedStyle(e).pointerEvents),'none');assert.notEqual(await page.locator('#tutorial-finger').evaluate(e=>getComputedStyle(e).animationName),'none');await page.keyboard.press('Digit1');await advance(30);assert.equal((await state()).tutorial.time,s.tutorial.time);assert.equal((await state()).tutorial.gates[1].amount,0);await shot('02-finger');await page.locator('#gate').click();assert.equal(await page.locator('#tutorial-finger').isVisible(),false);await advance(4);assert.equal((await state()).tutorial.phase,'success');assert.equal((await state()).tutorial.score,5);});
 await check('independent failure is explained; safe retry supplies finger and Numpad input',async()=>{await next();assert.equal((await state()).tutorial.step,2);await advance(6);assert.equal((await state()).tutorial.phase,'retry');assert.deepEqual((await state()).tutorial.lives,[3,3,3,3]);assert.match(await page.locator('#tutorial-text').innerText(),/не отнимают жизни/);assert.equal(await page.locator('#effects').innerHTML(),'');await shot('03-safe-retry');await next();await advance(5);assert.equal((await state()).tutorial.fingerLane,0);await page.keyboard.press('Numpad1');await advance(4);assert.equal((await state()).tutorial.phase,'success');});
 await check('black plate: acknowledgement starts time, waiting wins, no tap finger',async()=>{await next();assert.equal((await state()).tutorial.phase,'black_read');assert.equal(await page.locator('#tutorial-finger').isVisible(),false);assert.equal(await page.locator('.plate.black.tutorial-focus').count(),1);await shot('04-black-instruction');const t=(await state()).tutorial.time;await advance(20);assert.equal((await state()).tutorial.time,t);await next();await advance(1);assert.ok((await state()).tutorial.time>t);await advance(5);assert.equal((await state()).tutorial.phase,'success');});
 await check('two staggered cars use separate gates, then clean main shift',async()=>{await next();await advance(1.3);assert.equal((await state()).tutorial.cars.filter(Boolean).length,2);assert.notEqual((await state()).tutorial.cars[0].plate,(await state()).tutorial.cars[1].plate);await shot('05-two-cars');await advance(3.25);await page.keyboard.press('Digit1');await advance(1.25);await page.keyboard.press('Digit2');await advance(4);assert.equal((await state()).tutorial.phase,'complete');await shot('06-complete');await next();clean(await state());assert.equal((await state()).remembered,true);assert.equal(await page.locator('#tutorial-finger').isVisible(),false);assert.equal(await page.locator('#training-panel').isVisible(),false);});
 await check('pause freezes tutorial, modal traps focus, resume retains finger',async()=>{await hook('start');await next();await advance(5);const t=(await state()).tutorial.time;await page.keyboard.press('Escape');await advance(10);assert.equal((await state()).mode,'paused');assert.equal((await state()).tutorial.time,t);assert.equal(await page.locator('#gate-zones').evaluate(e=>e.inert),true);assert.equal(await page.locator('#tutorial-finger').isVisible(),false);await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-fullscreen')),true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'start');if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();assert.equal((await state()).tutorial.phase,'tap');assert.equal(await page.evaluate(()=>document.activeElement.id),'gate');assert.equal(await page.locator('#tutorial-finger').isVisible(),true);});
 await check('skip clears every tutorial phase and cannot leak cars or rewards',async()=>{const fixtures=[()=>hook('start'),async()=>{await hook('start');await next();await advance(5);},async()=>{await first();await advance(6);},black,pair,async()=>{await hook('start');await page.keyboard.press('Escape');}];for(const setup of fixtures){await setup();if((await state()).mode==='paused')await page.locator('#dialog-skip').click();else await page.locator('#tutorial-skip').click();clean(await state());assert.equal(await page.locator('#effects').innerHTML(),'');}});
 await check('training remembered on reload; replay and restart remain available',async()=>{await page.reload();await page.waitForFunction(()=>window.__parkingTutorialTest);assert.match(await page.locator('#start').innerText(),/Участвовать/);assert.equal(await page.locator('#dialog-training').isVisible(),true);await page.locator('#dialog-training').click();assert.equal((await state()).mode,'tutorial');await hook('start');await page.locator('#tutorial-skip').click();await page.keyboard.press('Escape');await page.locator('#restart').click();clean(await state());await page.keyboard.press('Escape');await page.locator('#dialog-menu').click();await page.locator('#dialog-training').click();assert.equal((await state()).tutorial.phase,'read');});
 await check('result offers replay training and return to menu',async()=>{await page.evaluate(()=>window.__parkingLaneTest.reset({autoSpawn:false,difficultyAt:300}));for(let i=0;i<3;i++){await page.evaluate(()=>window.__parkingLaneTest.spawn({black:false}));await advance(2.6);}assert.equal((await state()).mode,'result');assert.equal(await page.locator('#dialog-training').isVisible(),true);assert.equal(await page.locator('#dialog-menu').isVisible(),true);await page.locator('#dialog-training').click();assert.equal((await state()).tutorial.phase,'read');await page.locator('#tutorial-skip').click();clean(await state());});
 await check('unavailable localStorage does not block skip or same-session preference',async()=>{await page.evaluate(()=>{window.__restoreStorage={get:Storage.prototype.getItem,set:Storage.prototype.setItem};Storage.prototype.getItem=Storage.prototype.setItem=function(){throw new Error('storage disabled');};});await hook('start');await hook('skip');clean(await state());await hook('menu');assert.match(await page.locator('#start').innerText(),/Участвовать/);await page.evaluate(()=>{Storage.prototype.getItem=window.__restoreStorage.get;Storage.prototype.setItem=window.__restoreStorage.set;});});
 await check('tutorial fits 1920 and 1366; finger target and plate stay inside lane',async()=>{for(const [width,height] of [[1920,1080],[1366,768]]){await page.setViewportSize({width,height});await page.waitForFunction(([w,h])=>innerWidth===w&&innerHeight===h&&Math.abs(document.querySelector('#stage').getBoundingClientRect().height-1080*Math.min(w/1920,h/1080))<.1,[width,height]);await hook('start');await next();await advance(5);const f=await page.locator('#tutorial-finger').boundingBox(),g=await page.locator('#gate').boundingBox(),p=await page.locator('.plate').boundingBox(),panel=await page.locator('#training-panel').boundingBox(),footer=await page.locator('.legend').boundingBox();const badge=await page.locator('#gate .gate-key').boundingBox();assert.ok(f.x+f.width<badge.x);assert.ok(f.x>=g.x&&f.x+f.width<=g.x+g.width);assert.ok(f.y>=g.y&&f.y+f.height<=g.y+g.height);assert.ok(p.x+p.width<g.x);assert.ok(p.y+p.height<=590*height/1080);assert.ok(panel.y+panel.height<footer.y);assert.equal(await page.locator('#training-panel').evaluate(e=>e.scrollWidth>e.clientWidth),false);await shot('07-finger-'+width);await black();await shot('08-black-'+width);}});
 await check('reduced motion keeps static hint and working input',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await hook('start');await next();await advance(5);assert.equal(await page.locator('#tutorial-finger').evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('#gate').click();await advance(4);assert.equal((await state()).tutorial.phase,'success');});
 await check('no renderer errors or remote requests; local font loaded',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.evaluate(()=>document.fonts.check('40px Pixel')),true);assert.deepEqual(await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>/^https?:/.test(r.name)).map(r=>r.name)),[]);});
 report.status='PASS';
}catch(error){report.status='FAIL';report.error=error.stack;console.error(error);process.exitCode=1;}
finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));if(app)await app.close();}


