import { _electron as electron } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const out=path.resolve('test-output');fs.mkdirSync(out,{recursive:true});
const data=fs.mkdtempSync(path.join(os.tmpdir(),'parking-ui-'));const env={...process.env,PARKING_TEST_DATA:data};delete env.ELECTRON_RUN_AS_NODE;
let app;const report=[];const errors=[];
async function run(name,fn){await fn();report.push({name,status:'PASS'});console.log('PASS '+name);}
try{
 app=await electron.launch({args:['.','--test-mode'],env,timeout:60000});
 const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));
 await page.waitForFunction(()=>window.__parkingTest&&document.querySelector('#world canvas'));
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1920,1080));
 await page.evaluate(()=>document.fonts.ready);
 const state=()=>page.evaluate(()=>window.__parkingTest.snapshot());
 const fixture=o=>page.evaluate(o=>window.__parkingTest.fixture(o),o);
 await run('offline boot, Russian UI, seeded ranking and screen fit',async()=>{assert.equal((await state()).mode,'lobby');assert.equal(await page.locator('#leader-list li').count(),10);assert.match(await page.locator('#leader-list').innerText(),/Вася/);assert.equal(await page.locator('#stage').evaluate(e=>e.scrollHeight),1080);await page.screenshot({path:path.join(out,'01-lobby.png')});});
 await run('empty nickname rejected and touchscreen keyboard enters Cyrillic and digits',async()=>{await page.getByRole('button',{name:'УЧАСТВОВАТЬ',exact:false}).click();assert.match(await page.locator('#name-error').innerText(),/Введи/);await page.locator('#keyboard').getByRole('button',{name:'А',exact:true}).click();await page.locator('#keyboard').getByRole('button',{name:'Н',exact:true}).click();await page.locator('#keyboard').getByRole('button',{name:'Я',exact:true}).click();await page.locator('#keyboard').getByRole('button',{name:'123',exact:true}).click();await page.locator('#keyboard').getByRole('button',{name:'7',exact:true}).click();assert.equal(await page.locator('#nickname').inputValue(),'АНЯ7');});
 await run('participate, 3-second countdown, keyboard white pass +5 and audio unlock',async()=>{await page.locator('#join-form button').click();assert.equal((await state()).mode,'countdown');await page.waitForFunction(()=>window.__parkingTest.snapshot().mode==='playing');await fixture({lane:0});await page.keyboard.press('Digit1');assert.equal((await state()).score,5);assert.equal((await state()).audioState,'running');});
 await run('pointer black pass -15 with Russian penalty and skid FX',async()=>{await fixture({lane:1,black:true});await page.locator('#gate-1').click();assert.equal((await state()).score,-10);assert.match(await page.locator('#toast').innerText(),/Черный список! Штраф 15 очков/);await page.screenshot({path:path.join(out,'02-penalty.png')});});
 await run('closed black explodes without life loss; closed white shows driver and loses life',async()=>{await fixture({lane:2,black:true});await page.evaluate(()=>window.__parkingTest.advance(.85));assert.equal((await state()).lives,3);assert.ok((await state()).fx.some(f=>f.type==='explode'));await page.screenshot({path:path.join(out,'03-explosion.png')});await fixture({lane:3});await page.evaluate(()=>window.__parkingTest.advance(.85));assert.equal((await state()).lives,2);assert.ok((await state()).fx.some(f=>f.type==='crash'));await page.screenshot({path:path.join(out,'04-driver.png')});});
 await run('pause freezes simulation and resume restores input',async()=>{await page.keyboard.press('Escape');const time=(await state()).time;await page.waitForTimeout(300);assert.equal((await state()).time,time);await page.locator('#resume').click();assert.equal((await state()).mode,'playing');});
 await run('gameplay layout at 1920x1080 and scaled 1366x768',async()=>{await page.evaluate(()=>{window.__parkingTest.setScene();window.__parkingTest.freeze();});await page.waitForTimeout(80);await page.screenshot({path:path.join(out,'05-gameplay.png')});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1366,768));await page.waitForTimeout(80);const box=await page.locator('#gate-3').boundingBox();assert.ok(box.width>=130&&box.height>=100);await page.screenshot({path:path.join(out,'06-scaled.png')});await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1920,1080));await page.keyboard.press('Escape');});
 await run('three lost lives end once and record final score to portable JSON',async()=>{for(let i=0;i<2;i++){await fixture({lane:i});await page.evaluate(()=>window.__parkingTest.advance(.85));}await page.waitForFunction(()=>window.__parkingTest.snapshot().mode==='result');await page.waitForFunction(()=>!document.querySelector('#again').disabled);assert.equal((await state()).lives,0);const disk=JSON.parse(fs.readFileSync(path.join(data,'leaderboard.json')));assert.ok(disk.entries.some(e=>e.name==='АНЯ7'&&e.score===185));await page.screenshot({path:path.join(out,'07-result.png')});});
 await run('idle autoplay after 30 seconds, exact wake text, demo does not save',async()=>{const before=fs.readFileSync(path.join(data,'leaderboard.json'),'utf8');await page.evaluate(()=>window.__parkingTest.idle());await page.waitForFunction(()=>window.__parkingTest.snapshot().mode==='attract');assert.match(await page.locator('#wake').innerText(),/Коснитесь, чтобы начать/);await page.waitForTimeout(800);assert.equal(fs.readFileSync(path.join(data,'leaderboard.json'),'utf8'),before);await page.screenshot({path:path.join(out,'08-attract.png')});await page.locator('#wake').click();assert.equal((await state()).mode,'lobby');assert.equal(await page.locator('#nickname').inputValue(),'');});
 await run('ten-minute end is a saved completed shift',async()=>{await page.locator('#nickname').fill('ЛИМИТ');await page.locator('#join-form button').click();await page.evaluate(()=>{window.__parkingTest.skipCountdown();window.__parkingTest.fixture();window.__parkingTest.time(599.9);window.__parkingTest.advance(.2);});await page.waitForFunction(()=>window.__parkingTest.snapshot().mode==='result');assert.equal((await state()).time,600);assert.match(await page.locator('#result-title').innerText(),/ОТЛИЧНАЯ/);});
 await run('no renderer exceptions or external web requests; navigation blocked',async()=>{assert.deepEqual(errors,[]);const remote=await app.evaluate(async({session})=>{try{await session.defaultSession.fetch('https://example.com');return 'allowed';}catch{return 'blocked';}});assert.equal(remote,'blocked');});
 console.log(`UI CHECKS: ${report.length} passed`);
}catch(error){report.push({status:'FAIL',error:error.stack});console.error(error);process.exitCode=1;}
finally{fs.writeFileSync(path.join(out,'ui-report.json'),JSON.stringify(report,null,2));if(app)await app.close();fs.rmSync(data,{recursive:true,force:true});}
