import {_electron as electron} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'output/playwright/lane');fs.mkdirSync(out,{recursive:true});
const host=path.join(out,'host.cjs'),file=path.join(root,'web-test/index.html');
// Offscreen painting supplies real animation frames without exposing a native test window.
fs.writeFileSync(host,`const {app,BrowserWindow}=require('electron');app.setPath('userData',${JSON.stringify(path.join(out,'profile'))});app.whenReady().then(()=>{const w=new BrowserWindow({show:false,width:1920,height:1080,webPreferences:{contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true}});w.loadFile(${JSON.stringify(file)},{query:{test:'1'}});});app.on('window-all-closed',()=>app.quit());`);
const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
let app;const report={date:new Date().toISOString(),engine:'Chromium, local web bundle',checks:[]},errors=[];
async function check(name,fn){await fn();report.checks.push(name);console.log('PASS '+name);}
try{
 app=await electron.launch({args:[host],env,timeout:45000});const page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>window.__parkingLaneTest);await page.evaluate(()=>document.fonts.ready);await page.setViewportSize({width:1920,height:1080});
 const snapshot=()=>page.evaluate(()=>window.__parkingLaneTest.snapshot());
 const fixture=async(options={})=>page.evaluate(options=>{window.__parkingLaneTest.reset({difficultyAt:options.tempo??0});window.__parkingLaneTest.spawn({black:options.black??false,type:options.type??'sedan'});},options);
 const advance=dt=>page.evaluate(dt=>window.__parkingLaneTest.advance(dt),dt);
 const shot=name=>page.screenshot({path:path.join(out,name+'.png'),scale:'css'});
 await check('Russian start screen, first-run training and skip to game',async()=>{await page.evaluate(()=>window.__parkingTutorialTest.clearSeen());assert.match(await page.locator('#dialog-title').innerText(),/контролем/);if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();assert.equal((await snapshot()).mode,'tutorial');await page.locator('#tutorial-skip').click();assert.equal((await snapshot()).mode,'playing');});
 await check('keyboard 2: rise first, then +5 at crossing, no visual instant rotation',async()=>{await fixture();await advance(4.55);await page.keyboard.press('Digit2');assert.equal((await snapshot()).score,0);await advance(.06);assert.ok((await snapshot()).gate.amount>0&&(await snapshot()).gate.amount<1);await shot('01-rising');await advance(.2);assert.equal((await snapshot()).score,5);assert.equal((await snapshot()).gate.amount,1);await shot('02-pass');});
 await check('early and late presses crash; driver feedback and one lost life',async()=>{await fixture();await page.keyboard.press('Digit2');await advance(4.81);assert.equal((await snapshot()).lives,2);await shot('03-crash');await fixture();await advance(4.74);await page.keyboard.press('Digit2');await advance(.07);assert.equal((await snapshot()).lives,2);});
 await check('pointer opens black: -15 and smoke; closed black explodes',async()=>{await fixture({black:true});await advance(4.55);await page.locator('#gate').click();await advance(.3);assert.equal((await snapshot()).score,-15);assert.match(await page.locator('#feedback').innerText(),/Штраф 15/);await shot('04-penalty');await fixture({black:true});await advance(4.87);assert.equal((await snapshot()).car.state,'exploded');assert.equal((await snapshot()).lives,3);await shot('05-explosion');});
 await check('pointer hover keeps barrier and explosion visible through hit target',async()=>{const bg=await page.locator('#gate').evaluate(e=>getComputedStyle(e).backgroundColor);assert.ok(bg.startsWith('rgba('),bg);assert.ok(parseFloat(bg.split(',')[3])<=.1,bg);});
 await check('final speed hides plate until midpoint; tempo switch cannot hide it again',async()=>{await fixture({tempo:300});await advance(.75);assert.equal(await page.locator('.plate').isVisible(),false);await advance(.05);assert.equal(await page.locator('.plate').isVisible(),true);await page.evaluate(()=>window.__parkingShiftTest.tempo(150));assert.equal((await snapshot()).car.revealAt,.5);assert.equal(await page.locator('.plate').isVisible(),true);await shot('06-reveal');});
 await check('holding key or clicking during pulse does not extend it; Numpad2 works',async()=>{await fixture();await page.keyboard.down('Digit2');const until=(await snapshot()).gate.pulseUntil;await advance(.1);await page.keyboard.down('Digit2');await page.locator('#gate').click();assert.equal((await snapshot()).gate.pulseUntil,until);await page.keyboard.up('Digit2');await advance(.85);await page.keyboard.press('Numpad2');assert.ok((await snapshot()).gate.pulseUntil>until);});
 await check('pause and visibility loss freeze time; resume retains scene',async()=>{await fixture();await advance(1);await page.keyboard.press('Escape');const t=(await snapshot()).time;await advance(2);assert.equal((await snapshot()).time,t);if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();await advance(.1);assert.ok((await snapshot()).time>t);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));delete document.hidden;});assert.equal((await snapshot()).mode,'paused');});
 await check('third loss shows restart; restart clears cars, score, pulse and effects',async()=>{await fixture({tempo:300});for(let i=0;i<3;i++){if(i)await page.evaluate(()=>window.__parkingLaneTest.spawn({black:false}));await advance(2.6);}assert.equal((await snapshot()).mode,'result');assert.equal((await snapshot()).lives,0);await shot('07-result');if(await page.locator('#nickname').isVisible())await page.locator('#nickname').fill('Тест');await page.locator('#start').click();const s=await snapshot();assert.equal(s.lives,3);assert.equal(s.time,0);assert.equal(s.score,0);assert.equal(s.car,null);assert.equal(s.gate.amount,0);assert.equal(await page.locator('#effects').innerHTML(),'');});
 await check('300-second shift ends and preserves final result',async()=>{await page.evaluate(()=>window.__parkingLaneTest.reset({autoSpawn:false}));await advance(301);assert.equal((await snapshot()).mode,'result');assert.equal((await snapshot()).reason,'time');assert.match(await page.locator('#dialog-title').innerText(),/Пять минут/);});
 await check('moving plates never cover gate target at 1920 or 1366, all 5 bodies',async()=>{
  for(const [width,height] of [[1920,1080],[1366,768]]){await page.setViewportSize({width,height});await page.waitForFunction(([w,h])=>innerWidth===w&&innerHeight===h&&Math.abs(document.querySelector('#stage').getBoundingClientRect().height-1080*Math.min(w/1920,h/1080))<.1,[width,height]);for(const type of ['sedan','crossover','minivan','truck','convertible']){
   await fixture({type});for(let i=0;i<16;i++){await advance(.299);const p=await page.locator('.plate').boundingBox(),g=await page.locator('#gate').boundingBox();assert.ok(p.x+p.width<=g.x);assert.ok(p.y>=400*height/1080&&p.y+p.height<=590*height/1080,JSON.stringify({width,height,type,p,g,viewport:await page.evaluate(()=>({w:innerWidth,h:innerHeight,stage:document.querySelector('#stage').getBoundingClientRect().toJSON()}))}));}
  }await fixture({type:'minivan'});await advance(3.8);await shot('08-layout-'+width);}
 });
 await check('requestAnimationFrame actually moves the car',async()=>{await fixture();const x=(await snapshot()).car.front;await page.evaluate(()=>window.__parkingLaneTest.realtime());await page.waitForTimeout(350);assert.ok((await snapshot()).car.front>x+30);});
 await check('local font loaded, no renderer errors, no external assets',async()=>{assert.equal(await page.evaluate(()=>document.fonts.check('40px Pixel')),true);assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>/^https?:/.test(r.name)).map(r=>r.name)),[]);});
 report.status='PASS';
}catch(error){report.status='FAIL';report.error=error.stack;console.error(error);process.exitCode=1;}
finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));if(app)await app.close();}
